name: OIDC-MSDO-DF-LINUX

# Controls when the workflow will run 
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      # checkout your code repository to scan
      - uses: actions/checkout@v3
      
      - name: security-devops-action
        uses: microsoft/security-devops-action@latest
        id: msdo
        with:
          # The command to run. Defaults to run.
          command: run # optional, default is all
          # A comma separated list of analyzer to run. Example bandit, binskim, container-mapping, eslint, templateanalyzer, terrascan, trivy.
          tools: 'trivy, credscan, checkov, templateanalyzer, terrascan, eslint' #, bandit, binskim #, container-mapping, eslint, templateanalyzer, terrascan
        env:
          DfdBackendServiceEnvironment: "PPE"
          GDN_RUN_BLAME: true
          #MSDO_VERSION: '0.200.0'
